[package]
name = "ashpaper"
version = "0.1.0"
authors = ["Shea Newton <shnewto@gmail.com>"]
edition = "2018"

[lib]
name = "ashpaper"
path = "src/lib.rs"

[dependencies]
wordsworth = "^0.1.0"
nom = "5.0.0"
